### ISSUE TITLE
Slightly glitchy point/line edit behaviour

### ISSUE THREAD

**Issue by kwinkunks** [ben-bougher/pickr#140]
Sometimes it's hard to grab a point to move it, or add a new point on the line. Part of the problem is that the mouseover cursor is not related to the actual aiblity to move or add.

I think attaching the mouse events with Raphael's handlers might make a more robust connection between the SVG objects and the mouse...?

**Comment by stevejpurves** [comment]
partially addressed in https://github.com/ben-bougher/pickr/pull/141 but there are still issues, 
- when a pick is added hover effect is lost until mouse moves again
- accuracy of pick pointer, do we need the magic '-2' or should a crosshair be used for picking?

**Comment by stevejpurves** [comment]
this takes it further https://github.com/ben-bougher/pickr/pull/143

outstanding issues:
- hover on segments still a little off, but isn't this about the cursor choice and the location of the hot zone on the arrow pointer?
- need to get neighbouring segments moving along with the point

**Comment by kwinkunks** [comment]
Closed by Steve's work. Thanks Steve!
