### ISSUE TITLE
Add points to either end of a line when picking

### ISSUE THREAD

**Issue by stevejpurves** [ben-bougher/pickr#142]
currently you can only add picks to one end of the line, to extend the other end you need to insert and move points.

maybe a double click action to change the 'active' end of the line?

**Comment by kwinkunks** [comment]
I think how we tackle this is related to #22. I was thinking a double-click would end the current segment and start a new one. We're going to need that functionality pretty soon.

Another way to append to the other end could be to switch the 'live' end to whatever is closest... that might seem a bit like magic though.

**Comment by stevejpurves** [comment]
yeah magic isn't good. as you say #22 looks like the one to tackle

**Comment by kwinkunks** [comment]
Closing this and leaving the drawing enhancement wishlist in #22.

**Comment by stevejpurves** [comment]
Good call
