### ISSUE TITLE
Logout Button logs out of entire Google Account

### ISSUE THREAD

**Issue by JesperDramsch** [ben-bougher/pickr#152]
The log out on the webpage logs out of the entire Google Account (Google-wide), as opposed to logging out of the application.

**Comment by kwinkunks** [comment]
Good one Jesper, always been a problem. We have to reset a cookie or two... This looks like it will help http://stackoverflow.com/a/14178401/3381305

**Comment by kwinkunks** [comment]
Fixed by 8ce8363cfa15e83e2d304112381cad1e2e7abd1b
