### ISSUE TITLE
Results Page broken

### ISSUE THREAD

**Issue by ben-bougher** [ben-bougher/pickr#157]
76.11.41.65 - Ben.Bougher [19/Feb/2015:04:18:00 -0800] "GET /results?image_key=5724160613416960 HTTP/1.1" 302 118 "http://pickthis.io/library" "Mozilla/5.0 Looks like there is an indexing error when loading the results page on the Brazil image. Maybe something has gotten out of sync when we deleted some interpretations?

(Windows NT 6.1; WOW64; rv:29.0) Gecko/20100101 Firefox/29.0" "pickthis.io" ms=15698 

cpu_ms=26584 cpm_usd=0.000013 app_engine_release=1.9.17 instance=00c61b117c44fbf0e721f0ca95712a4e24d672bb

E 2015-02-19 04:18:00.899

index (1000) out of range (0<=index<999) in dimension 1

**Comment by kwinkunks** [comment]
Still bug squishing

**Comment by kwinkunks** [comment]
Fixed with some refactoring in pickthis.py.
