### ISSUE TITLE
Priorities on issues

### ISSUE THREAD

**Issue by JesperDramsch** [ben-bougher/pickr#166]
This is more a suggestion than an issue.

Could be introduce a priority system?

Now we have [[bug]] and [[enhancement]].
With around 70 issues, I think some sort of priority system would be very helpful to start tackling the important stuff first. Maybe just [[Urgent]], [[Soon]], [[Backburner]] would do the trick (better names obviously). This would also help distinguish between bugs and enhancements.

**Comment by kwinkunks** [comment]
Agreed. We try to do this with 'Milestone'. It's not quite the same thing I guess, but should do the job. I need to manage the list a bit, as I don't think we've been very rigorous about release numbers and so on. I'll do some tidying now.
